// vue-todo/src/App.vue
<template>
  <div id="app">
    <h2>タスク</h2>
    <div>
      <input type="text" v-model="newTodoName">
      <button type="submit" v-on:click="createTodo()">タスク作成</button>
    </div>
    <ul>
      <li><button type="submit" v-on:click="showTodoType = 'all'">すべて</button></li>
      <li><button type="submit" v-on:click="showTodoType = 'active'">未完タスク一覧</button></li>
      <li><button type="submit" v-on:click="showTodoType = 'complete'">完了タスク一覧</button></li>
    </ul>
    <todos :todos="this.todos" :updateIsComplete="updateIsComplete" :updateTodo="updateTodo" :deleteTodo="deleteTodo" />
  </div>
</template>

<script>
import { db } from './main'
import Todos from './components/Todos.vue'

export default {
  components: {
    'todos': Todos
  },
  name: 'App',
  created: function() {
    this.db = db;
    this.db.collection('todos').onSnapshot(snapshots => {
      this.todos = []
      snapshots.forEach(snapshot => {
        this.todos.push(snapshot.data())
      })
    });
  },
  computed: {
    filteredTodos: function () {
      if (this.showTodoType == 'all') {
        return this.todos;
      } else {
        let showIsComplete = false;
        if (this.showTodoType == 'complete') { showIsComplete = true }
        let filterTodos = {};
        for (var key in this.todos) {
          let todo = this.todos[key];
          if (todo.isComplete == showIsComplete) { filterTodos[key] = todo; }
        }
        this.todos = filterTodos
      }
    }
  },
  methods: {
    createTodo: function() {
      if (this.newTodoName == "") return;
      const todoRef = this.db.collection('todos').doc()
      const todoId = todoRef.id
      this.db.collection('todos').doc(todoId).set({
        name: this.newTodoName,
        isComplete: false,
        id: todoId
      })
      this.newTodoName = "";
    },
    updateIsComplete(todo){
      todo.isComplete = !todo.isComplete
      this.db.collection('todos').doc(todo.id).delete();
    },
    deleteTodo(todo){
      this.db.collection('todos').doc(todo.id).delete()
    },
    updateTodo(todo, updateText){
      todo.name = updateText
      this.db.collection('todos').doc(todo.id).set(todo)
    }
  },

  data () {
    return {
      db: null,
      newTodoName: '',
      showTodoType: 'all',
      todos: []
    }
  }
}
</script>

<style>
* {
  list-style: none;
}
body {
  width: 500px;
  margin: 30px auto;
  text-align: start;
}
.todos {
  display: flex;
  padding: 10px;
}
</style>

// react-todo/src/App.js
import React, { useState, useEffect } from 'react'
import { db } from './db'
import { Todolist } from './components/Todolist'
import { Form } from './components/Form'

export const App = () => {
  const [todos, setTodos] = useState([])
  const [todoType, setTodoType] = useState('all')

  const deleteTodo = (id) => {
    db.collection('todos').doc(id).delete()
  }

  const isCompleteToggle = (todo) => {
    db.collection('todos').doc(todo.id).set({
      todo: todo.todo,
      id: todo.id,
      isComplete: !todo.isComplete
    })
  }

  const updateTodo = (todo, text, setText, setEdit) => {
    db.collection('todos').doc(todo.id).set({
      id: todo.id,
      todo: text,
      isComplete: todo.isComplete
    })
    .then(() => {
      setText('')
      setEdit(false)
    })
  }


  const todosFetch = async() => {
    let newTodos = []
    await db.collection('todos').get()
      .then(snapshot => {
        snapshot.docs.forEach(doc => {
          const data = doc.data()
          newTodos.push(data)
        })
      })
    return newTodos
  }

  const changeTodoType = async () => {
    if (todoType === "all") {
      const todolist = await todosFetch()
      console.log(todolist)
      setTodos(todolist)
    } else {
      let showIsComplete = false
      if (todoType === 'complete') { showIsComplete = true }
      const todolist = await todosFetch()
      const filterTodos = todolist.filter(todo => todo.isComplete === showIsComplete)
      console.log(filterTodos)
      setTodos(filterTodos)
    }
  }

  useEffect(() => {
    changeTodoType()
  }, [todoType, updateTodo])

  return (
    <div>
      <div>
        <h2>React ToDo</h2>
      </div>
      <div style={{ margin: "30px"}}>
        <Form setTodoType={setTodoType} todoType={todoType} />
        <Todolist todos={todos} deleteTodo={deleteTodo} isCompleteToggle={isCompleteToggle} updateTodo={updateTodo}/>
      </div>
    </div>
  )
}
