// react-todo/src/components/TodoItem.js
import React, { useCallback, useState } from 'react'
import { db } from '../db'

export const TodoItem = ({ todo, deleteTodo, isCompleteToggle, updateTodo }) => {
  const [text, setText] = useState("")
  const [edit, setEdit] = useState(false)

  const inputText = useCallback((event) => {
    setText(event.target.value)
  }, [setText])

  return (
    <div>
      <li style={{ display: 'flex' }}>
        <div style={{ padding: "10px" }}>
          <input
            type="checkbox"
            checked={todo.isComplete}
            onClick={() => isCompleteToggle(todo)}
          />
        </div>
        <div style={{ padding: '10px' }}>
          {todo.todo}
        </div>
        <button
          style={{ margin: '10px' }}
          onClick={() => deleteTodo(todo.id)}
        >
          delete
        </button>
        <button
          style={{ margin: '10px' }}
          onClick={() => setEdit(!edit)}
        >
          edit
        </button>
        {edit && (
          <div style={{ margin: '10px' }}>
            <input
              type="text"
              value={text}
              onChange={(event) => inputText(event)}
            />
            <button
              onClick={() => updateTodo(todo, text, setText, setEdit)}
            >
              submit
            </button>
          </div>
        )}
      </li>
    </div>
  )
}

// vue-todo/src/components/TodoItem.vue
<template>
  <div>
      <li style="display: flex">
        <div style="padding: 10px">
          <input type="checkbox" v-model="todo.isComplete" v-on:click="IsCompleteToggle(todo)">
        </div>
        <div style="padding: 10px">
        {{ todo.todo }}
        </div>
        <button style="margin: 10px" v-on:click="deleteTodo(todo.id)">delete</button>
        <button style="margin: 10px" v-on:click="edit=!edit" >edit</button>
        <div v-show="edit" style="margin: 10px" class='update__text'>
          <input type="text" v-model="updateText" :placeholder="todo.todo" >
          <button v-on:click="updateTodo(todo, updateText)">submit</button>
        </div>
      </li>
  </div>
</template>

<script>
import { db } from '../db'

export default {
  name: 'TodoItem',
  data() {
    return {
      edit: false,
      updateText: "",
    }
  },
  props: {
    todo: {
      todo: String,
      id: String,
      isComplete: Boolean
    },
    IsCompleteToggle: Function,
    deleteTodo: Function
  },
  methods: {
    updateTodo(todo, text) {
      db.collection('todos').doc(todo.id).set({isComplete: todo.isComplete, todo: text, id: todo.id})
      .then(() => {
        this.edit = false
        this.updateText = ""
      })
    }
  }
}
</script>
