// angular-todo/src/app/pages/todo/todo/todo-item/todo-item.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { db } from 'src/db';

interface Todo {
  todo: string,
  id: string
  isComplete: boolean
}

@Component({
  selector: 'app-todo-item',
  templateUrl: './todo-item.component.html',
  styleUrls: ['./todo-item.component.css']
})

export class TodoItemComponent implements OnInit {

  @Input() todo: Todo
  @Input() isCompleteToggle: (todo: Todo) => void
  @Input() deleteTodo: (id: String) => void
  @Input() fetchTodo: () => void

  updateText = ""
  edit = false

  constructor() { }
  ngOnInit(): void {
  }

  inputUpdateTodo = (text: string) => {
    this.updateText = text
  }

  updateTodo = (todo) => {
    db.collection('todos').doc(todo.id).set({
      isComplete: todo.isComplete,
      todo: this.updateText,
      id: todo.id
    })
      .then(() => {
        const updateTextForm: any = document.getElementById("update-todo-form")
        updateTextForm.value = ""
        this.updateText = ""
        this.edit = false
        this.fetchTodo()
    })
  }
}

// vue-todo/src/components/TodoItem.vue
<template>
  <div>
      <li style="display: flex">
        <div style="padding: 10px">
          <input type="checkbox" v-model="todo.isComplete" v-on:click="IsCompleteToggle(todo)">
        </div>
        <div style="padding: 10px">
        {{ todo.todo }}
        </div>
        <button style="margin: 10px" v-on:click="deleteTodo(todo.id)">delete</button>
        <button style="margin: 10px" v-on:click="edit=!edit" >edit</button>
        <div v-show="edit" style="margin: 10px" class='update__text'>
          <input type="text" v-model="updateText" :placeholder="todo.todo" >
          <button v-on:click="updateTodo(todo, updateText)">submit</button>
        </div>
      </li>
  </div>
</template>

<script>
import { db } from '../db'

export default {
  name: 'TodoItem',
  data() {
    return {
      edit: false,
      updateText: "",
    }
  },
  props: {
    todo: {
      todo: String,
      id: String,
      isComplete: Boolean
    },
    IsCompleteToggle: Function,
    deleteTodo: Function
  },
  methods: {
    updateTodo(todo, text) {
      db.collection('todos').doc(todo.id).set({isComplete: todo.isComplete, todo: text, id: todo.id})
      .then(() => {
        this.edit = false
        this.updateText = ""
      })
    }
  }
}
</script>
