// Angular-todo/src/app/todo/todo/todo.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { db } from '../../../db';

interface Todo {
  todo: string,
  id: string,
  isComplete: boolean
}

type TodoType = "all" | 'active' | 'complete'

@Component({
  selector: 'app-todo',
  templateUrl: './todo.component.html',
  styleUrls: ['./todo.component.css']
})
export class TodoComponent implements OnInit {

  todos: Todo[];
  todo = ""
  todoType: TodoType = 'all'

  constructor() { }
  ngOnInit(): void {
    this.fetchTodo()
  }

  isCompleteToggle = (todo: Todo) => {
    console.log(todo)
    db.collection('todos').doc(todo.id).set({
      todo: todo.todo,
      id: todo.id,
      isComplete: !todo.isComplete
    })
  }

  deleteTodo = (id: string) => {
    db.collection('todos').doc(id).delete()
    .then(() => this.fetchTodo())
  }

  addTodo = () => {
    const ref = db.collection('todos').doc()
    console.log(this.todo)
    const todoId = ref.id
    db.collection('todos').doc(todoId).set({
      id: todoId,
      todo: this.todo,
      isComplete: false
    })
      .then(() => {
        const textForm:any = document.getElementById("todo-form")
        textForm.value = ""
        this.todo = ""
        this.fetchTodo()
    })
  }

  inputTodo = (text: string) => {
    this.todo = text
  }

  fetchTodo = () => {
    db.collection('todos').get()
      .then(snapshot => {
        let todolist = []
        snapshot.docs.forEach(doc => {
          const data = doc.data()
          todolist.push(data)
        })
        this.todos = todolist
    })
  }

  returnTodos = async () => {
    let todolist = []
    await db.collection('todos').get()
      .then(snapshot => {
        snapshot.docs.forEach(doc => {
          const data = doc.data()
          todolist.push(data)
        })
      })
    return todolist
  }

  setTodoType = async (todoType: TodoType) => {
    if (todoType === "all") {
      this.fetchTodo()
    } else {
      let showIsComplete = false
      if (todoType === 'complete') { showIsComplete = true }
      const todolist = await this.returnTodos()
      const filterTodos = todolist.filter((todo: Todo) => todo.isComplete === showIsComplete)
      this.todos = filterTodos
    }
  }
}

// react-todo/src/pages/Todo.jsx
import React, { useState, useEffect } from 'react'
import { db } from '../db'
import { Todolist } from '../components/Todolist'
import { Form } from '../components/Form'

export const Todo = () => {
  const [todos, setTodos] = useState([])
  const [todoType, setTodoType] = useState('all')

  const deleteTodo = (id) => {
    db.collection('todos').doc(id).delete()
  }

  const isCompleteToggle = (todo) => {
    db.collection('todos').doc(todo.id).set({
      todo: todo.todo,
      id: todo.id,
      isComplete: !todo.isComplete
    })
  }

  const updateTodo = (todo, text, setText, setEdit) => {
    db.collection('todos').doc(todo.id).set({
      id: todo.id,
      todo: text,
      isComplete: todo.isComplete
    })
    .then(() => {
      setText('')
      setEdit(false)
    })
  }


  const todosFetch = async() => {
    let newTodos = []
    await db.collection('todos').get()
      .then(snapshot => {
        snapshot.docs.forEach(doc => {
          const data = doc.data()
          newTodos.push(data)
        })
      })
    return newTodos
  }

  const changeTodoType = async () => {
    if (todoType === "all") {
      const todolist = await todosFetch()
      console.log(todolist)
      setTodos(todolist)
    } else {
      let showIsComplete = false
      if (todoType === 'complete') { showIsComplete = true }
      const todolist = await todosFetch()
      const filterTodos = todolist.filter(todo => todo.isComplete === showIsComplete)
      console.log(filterTodos)
      setTodos(filterTodos)
    }
  }

  useEffect(() => {
    changeTodoType()
  }, [todoType, updateTodo])

  return (
    <div>
      <div>
        <h2>React ToDo</h2>
      </div>
      <div style={{ margin: "30px"}}>
        <Form setTodoType={setTodoType} todoType={todoType} />
        <Todolist todos={todos} deleteTodo={deleteTodo} isCompleteToggle={isCompleteToggle} updateTodo={updateTodo}/>
      </div>
    </div>
  )
}
