// angular-todo/src/app/pages/account/signup/signup.component.ts
import { Component, OnInit } from '@angular/core';
import { Password } from '../../../class/user';
import { SessionService } from '../../../service/session.service';

@Component({
  selector: 'app-signup',
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.css']
})
export class SignupComponent implements OnInit {

  public account = new Password();

  constructor(private session: SessionService) {}

  ngOnInit(): void {
  }

  submitSignUp(e: Event): void {
    e.preventDefault();
    if (this.account.password !== this.account.passwordConfirmation) {
      alert('パスワードが異なります。');
      return;
    }
    this.session.signup(this.account);
  }
}
<div class="formlist">
  <h2>
    sign_up
  </h2>
  <form (ngSubmit)="submitSignUp($event)" #signUpForm="ngForm">
    <input
      type="text"
      [(ngModel)]="account.name"
      #name="ngModel"
      placeholder="username"
      required autofocus
    >
    <input
      type="email"
      [(ngModel)]="account.email"
      #email="ngModel"
      placeholder="email"
    >
    <input
      type="password"
      [(ngModel)]="account.password"
      #password="ngModel"
      placeholder="password"
      required autofocus
    >
    <input
      type="password"
      [(ngModel)]="account.passwordConfirmation"
      #confirmPassword="ngModel"
      placeholder="confirm password"
      required autofocus
    >
    <div class="margin-10">
      <button
        type="submit"
        [disabled]="!signUpForm.form.valid"
      >
        sign up
      </button>
    </div>
  </form>
  <a router-link to="account/sign_in">alreday have email</a>
</div>

// vue-todo/src/pages/SignUp.vue
<template>
  <div class="formlist">
    <h2>
      sign_up
    </h2>
    <input type="text" v-model="name" placeholder="username">
    <input type="email" v-model="email" placeholder="email">
    <input type="password" v-model="password" placeholder="password">
    <input type="password" v-model="confirmPassword" placeholder="confirm password">
    <div class="margin-10">
      <button v-on:click="signUp()">sign up</button>
    </div>
    <router-link to="/sign_in">alreday have email</router-link>
  </div>
</template>

<script>
import { auth, db, timestamp } from '../db'

export default {
  name: 'SignUp',
  data() {
    return {
      name: "",
      email: "",
      password: "",
      confirmPassword: ""
    }
  },
  methods: {
    signUp() {
      if (this.name === "" || this.email === "" || this.password === ""){
        alert(('必須項目入れんかい'))
        return false
      }
      if(this.password !== this.confirmPassword){
        alert('パスワード確認せんかい')
        return false
      }
      auth.createUserWithEmailAndPassword(this.email, this.password).then((result) => {
        const user = result.user
        if (user) {
          const id = user.uid
          const data = {
            id: id,
            name: this.name,
            email: this.email,
            created_at: timestamp.now()
          }
          db.collection('users').doc(id).set(data).then(() => {
            this.$router.push('/sign_in')
          })
        }
      })
    }
  }
}
</script>
