// angular-todo/src/app/pages/account/signin/signin.component.ts
import { Component, OnInit } from '@angular/core';
import { SessionService } from '../../../service/session.service';
import { Password } from '../../../class/user';

@Component({
  selector: 'app-signin',
  templateUrl: './signin.component.html',
  styleUrls: ['./signin.component.css']
})
export class SigninComponent implements OnInit {

  public account = new Password();

  constructor(private sessionService: SessionService) { }

  ngOnInit() {
  }

  submitLogin(e: Event) {
    e.preventDefault();
    this.sessionService.login(this.account);
  }
}
<div class="formlist">
  <h2>
    sign_in
  </h2>
  <form (ngSubmit)="submitLogin($event)" #loginForm="ngForm">
    <input
      type="email"
      name="email"
      [(ngModel)]="account.email"
      #email="ngModel"
      placeholder="email"
      required
      autofocus
    >
    <input
      type="password"
      name="password"
      [(ngModel)]="account.password"
      #password="ngModel"
      placeholder="password"
      required
      autofocus
    >
    <div class="margin-10">
      <button
      type="submit"
      [disabled]="!loginForm.form.valid"
      >
        sign in
      </button>
    </div>
  </form>
  <a router-link to="/sign_up">create account</a>
</div>

// vue-todo/src/pages/SignIn.vue
<template>
  <div class="formlist">
    <h2>
      sign_in
    </h2>
    <input type="email" v-model="email" placeholder="email">
    <input type="password" v-model="password" placeholder="password">
    <div class="margin-10">
      <button v-on:click="signIn()">sign in</button>
    </div>
    <router-link to="/sign_up">create account</router-link>
  </div>
</template>

<script>
import { auth, db } from '../db'

export default {
  name: 'SignIn',
  data() {
    return {
      email: "",
      password: "",
    }
  },
  methods: {
    signIn() {
      if (this.email === "" || this.password === "") {
        alert('必須項目入れんかい')
        return false
      }
      auth.signInWithEmailAndPassword(this.email, this.password)
      .then((result) => {
        const user = result.user
        if (user) {
          db.collection('users').doc(user.uid).get()
          .then(() => {
            this.$router.push('/')
          })
        }
      })
    }
  }
}
</script>
